### PR TITLE
Not yet ready for GF

### PR DESCRIPTION
**Pull request by RosaWagner**
Hellooo
So I added everything to build the fonts. You will need a virtual environment to not create conflicts (because of the noto tools).

**In the Trispace folder:**
```
$ python3 -m venv env
$ source env/bin/activate
$ pip3 install -r requirements.txt
```
Then you can run the builds from the sources folder, it activates automatically the venv. 
The variable font only contains weight instances to match the spec. 

**This is your to do list:**

- [ ] DZ, LJ Nj etc > these ligatures are supposed to be « one » glyph, so width is too wide
- [ ] decompose and merge glyphs like oslash, zeroslash, peseta, peso… (where a shape is crossing another shapes’ closed countershape)
- [ ] decompose and merge glyphs like thorn (at least the vertical bar)
- [ ] decompose all comb accents
- [ ] reinsert correct vietnamese comb accent in small caps
- [ ] decomposed transformed components (in red)
- [ ] reposition dot of ldot.sc
- [ ] merge glyphs like oe, ae, asterisk (too much rendering issues with the accumulated overlaps)
- [ ] not the right Caron in tcaron
- [ ] avoid nested components like in fractions
- [ ] semicolon is weirdly positioned
- [ ] periodcentered.loclCAT should have zero width
- [ ] typoAscender has to go over the grave accent of Agrave

### CODE REVIEW

**Comment by sursly** [comment]
OK I think I understand. Should I run those terminal commands you posted above and THEN merge the pull request?

**Comment by RosaWagner** [comment]
you can merge before ;) In any case, you don't to build the fonts before making the corrections

**Comment by RosaWagner** [comment]
The color code is: base glyphs = blue, composite glyphs=grey, mixed composites=yellow, transformed components=red.
It would be nice to catch nested components, but as you know I still don't know how to write scripts from scratch :(

**Comment by sursly** [comment]
Gotcha, thanks! I'll get started. I have a custom list that should have all my nested components, but since I make that manually too, I miss some. Will share it though!

**Comment by sursly** [comment]
Ok, pushing out an update now. I haven't had luck with getting the new VF build to work from the script. I had to modify a bunch of things in the static script, and change some permissions, so we might not be solid there yet. But the glyphs source file should look good :p take a look, I think I got all of the items on your list above 👆

**Pull request merged**
